### ISSUE TITLE
Todo's not showing after post. 

### ISSUE THREAD

**Issue by Tzikas** [Gethyl/RealTimeTodo#1]
I'm able to start up your example, but the Todos won't post and I'm getting this in error in the client side console:   

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
polling-xhr.js:261 GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=Ln0L7Ao net::ERR_CONNECTION_REFUSED
```

I tried with and without running a mongod instance.

**Comment by Gethyl** [comment]
Hi, I tried now but I was not able to reproduce the issue. Only time I was able to get  ERR_CONNECTION_REFUSED was when my server was not up. Did you bring up the server as well using 

`npm run server`

**Comment by Tzikas** [comment]
I had to run both `npm run server` and `npm start`  and '`mongod` and it worked.  Previously I had only run `npm start` and `mongod`.  Is there a way to add `npm run server` functionality to `npm start`?  If I deployed to heroku would any special adjustments need to be made?  

THANK YOU VERY MUCH :)

**Comment by Gethyl** [comment]
You're welcome :)

The simplest way in this todo example would be as follows in `package.json`. Add into script a new command

`"start-both": "babel-node server.js | npm run start"`

While deploying do consider that, webpack dev server compiles in memory and doesn't write to a physical destination. Rather I would recommend to deploy your files to Heroku and build using webpack and not webpack-dev-server. 

I hope its okay to close the issue as it is resolved?

**Comment by Tzikas** [comment]
Yes thank you

**Comment by Tzikas** [comment]
One last question.  Why does it say:
 `socket = io.connect("http://localhost:3000")` & `serve.listen(3000,()=> {console.log("+++Gethyl Express Server with Socket Running!!!")})` 

And still show up under localhost:8080 ?

**Comment by Gethyl** [comment]
That is because `http://localhost:3000` is your actual backend server. `http://localhost:8080` is just your webpack-dev-server to build your JS files (& any other files for the client)
